language: node_js

node_js:
  - stable

install:
  - npm install https://github.com/fwalzel/handlebars-i18n

script:
  - npm test

after_success: 'npm run coveralls'

after_failure:
  - cat /Users/travis/.npm/_logs/*.log