os: osx

language: node_js

node_js:
  - stable

before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

install:
  - npm install handlebars-i18n handlebars i18next intl

script:
  - npm test

after_success: 'npm run coveralls'