name: CI

on: [create, pull_request, push]

env:
  IMAGE_ID: ${{ github.repository }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2.3.4
      - name: Build
        run: |
          npm i
          npm run test
  semantic-release:
    if: github.event_name != 'pull_request'
    name: Semantic Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2.5.3
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
